spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DEMO_MYBATIS_DB_URL:jdbc:mysql://127.0.0.1:3306/mybatis_plus?serverTimezone=GMT%2B8}
spring.datasource.username=${YYGH_MYSQL_USERNAME:root}
spring.datasource.password=${YYGH_MYSQL_PASSWORD:}

#mybatis��־
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

