# ����˿�
server.port=8202
# ������
spring.application.name=service-cmn

# �������ã�dev��test��prod
spring.profiles.active=dev

# mysql���ݿ�����
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=${YYGH_CMN_DB_URL:jdbc:mysql://127.0.0.1:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai}
spring.datasource.username=${YYGH_MYSQL_USERNAME:root}
spring.datasource.password=${YYGH_MYSQL_PASSWORD:}

#����json��ȫ��ʱ���ʽ
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

spring.redis.host=${YYGH_REDIS_HOST:127.0.0.1}
spring.redis.port=6379
spring.redis.database= 0
spring.redis.timeout=1800000

spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-wait=-1
#��������ȴ�ʱ��(������ʾû����)
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=0

# nacos�����ַ
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

#����mapper xml�ļ���·��
#mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/mapper/xml/*.xml
#mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/mapper/xml/*.xml
# nacos�����ַ
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

#����sentinel
#feign.sentinel.enabled=true
#����sentinel��ַ
#spring.cloud.sentinel.transport.dashboard=http://127.0.0.1:8858

#mongodb��ַ
#spring.data.mongodb.host=192.168.44.163
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=yygh_hosp

#rabbitmq��ַ
#spring.rabbitmq.host=127.0.0.1
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

#logging.level.root=DEBUG