# ����˿�
server.port=8204
# ������
spring.application.name=service-msm

#����json��ȫ��ʱ���ʽ
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

spring.redis.host=${YYGH_REDIS_HOST:127.0.0.1}
spring.redis.port=6379
spring.redis.database= 0
spring.redis.timeout=1800000
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-wait=-1
#��������ȴ�ʱ��(������ʾû����)
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=0

# nacos�����ַ
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

aliyun.sms.regionId=default
aliyun.sms.accessKeyId=${ALIYUN_SMS_ACCESS_KEY_ID:}
aliyun.sms.secret=${ALIYUN_SMS_SECRET:}

#rabbitmq��ַ
spring.rabbitmq.host=${YYGH_RABBITMQ_HOST:127.0.0.1}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

